#
# Copyright (C) 2010 - 2014 Eluna Lua Engine <http://emudevs.com/>
# This program is free software licensed under GPL version 3
# Please see the included DOCS/LICENSE.TXT for more information
#

language:
    cpp

compiler:
    - gcc
    - clang

# Only get newest commit
git:
    depth: 1

before_install:
# Install ACE
# Get ACE
    - wget http://download.dre.vanderbilt.edu/previous_versions/ACE-6.0.3.tar.gz > /dev/null
# Unzip ACE to TrinityCore/
    - tar xzf ACE-6.0.3.tar.gz > /dev/null
# Go to TrinityCore/ACE_wrappers
    - cd ACE_wrappers/
# Create TrinityCore/ACE_wrappers/build
    - mkdir build
# Go to TrinityCore/ACE_wrappers/build
    - cd build
# Install ACE system wide:
    - ../configure --disable-ssl > /dev/null
    - make -i --jobs=4 > /dev/null
    - sudo make -i --jobs=4 install > /dev/null
# Go to TrinityCore/
    - cd ../../

script:
# Create TrinityCore/BUILD
    - mkdir BUILD
# Create TrinityCore/SERVER
    - mkdir SERVER
# Go to TrinityCore/BUILD
    - cd BUILD
# Run cmake and set the BUILD directory as target for solution
    - cmake ../ -DPREFIX=/SERVER -DWITH_WARNINGS=1
# Compile (with 4 cores)
    - make --jobs=4
