language:
    cpp

compiler:
    - gcc
    - clang

# Only get newest commit
git:
    depth: 1
    
before_install:
# Install ACE
# Get ACE
    - wget http://download.dre.vanderbilt.edu/previous_versions/ACE-6.0.3.tar.gz
# Unzip ACE to TrinityCore/
    - tar xvzf ACE-6.0.3.tar.gz
# Go to TrinityCore/ACE_wrappers
    - cd ACE_wrappers/
# Create TrinityCore/ACE_wrappers/build
    - mkdir build
# Go to TrinityCore/ACE_wrappers/build
    - cd build
# Must install locally? Testing system wide:
    - ../configure --disable-ssl
    - make
    - sudo make install
# Go to TrinityCore/
    - cd ../../

script:
# Create TrinityCore/BUILD
    - mkdir BUILD
# Create TrinityCore/SERVER
    - mkdir SERVER
# Go to TrinityCore/BUILD
    - cd BUILD
# Run cmake and set the BUILD directory as target for solution
    - cmake ../ -DPREFIX=/SERVER -DWITH_WARNINGS=1
# Compile (with 4 cores)
    - make -j4
